### ISSUE TITLE
Error in Python 2.7.2

### ISSUE THREAD

**Issue by agude** [charles-uno/python-new-pool-bug#1]
I'm using Python 2.7.2 from Anaconda: `Python 2.7.12 :: Anaconda custom (64-bit)`

I get the following error: 

```
$python newpool.py

Called Foo.__new__ with args = (u'TIMESTAMP', u'INPUT0')
Called Foo.__new__ with args = ('TIMESTAMP OUTPUT0',)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/agude/bin/anaconda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/agude/bin/anaconda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/agude/bin/anaconda/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
    task = get()
  File "newpool.py", line 30, in __new__
    raise ValueError( 'Bad Foo input: ' + repr(args) )
ValueError: Bad Foo input: ('TIMESTAMP OUTPUT0',)

Traceback (most recent call last):
  File "newpool.py", line 49, in <module>
    main()
  File "newpool.py", line 20, in main
    print( getter.get(timeout=3) )
  File "/home/agude/bin/anaconda/lib/python2.7/multiprocessing/pool.py", line 563, in get
    raise TimeoutError
multiprocessing.TimeoutError
Traceback (most recent call last):
  File "/home/agude/bin/anaconda/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()
  File "/home/agude/bin/anaconda/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/agude/bin/anaconda/lib/python2.7/multiprocessing/pool.py", line 497, in _terminate_pool
    assert result_handler.is_alive() or len(cache) == 0
AssertionError
```

**Comment by agude** [comment]
It works with `goo` instead of `foo`.

**Comment by agude** [comment]
You can close this. The solution is to add [`__reduce__`](https://docs.python.org/2/library/pickle.html#pickling-and-unpickling-extension-types) so that `multiprocessing.pool()` can pickle the object.

See: https://bugs.python.org/issue30018#msg291299
