### ISSUE TITLE
Error in Python 3.5.2

### ISSUE THREAD

**Issue by agude** [charles-uno/python-new-pool-bug#2]
I'm using Python 3.5.2 from the Ubuntu 16.04 default repository: `Python 3.5.2`

I get the following error:

```
$python3 newpool.py

Called Foo.__new__ with args = ('TIMESTAMP', 'INPUT0')
Called Foo.__new__ with args = ('TIMESTAMP OUTPUT0',)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 429, in _handle_results
    task = get()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
  File "newpool.py", line 30, in __new__
    raise ValueError( 'Bad Foo input: ' + repr(args) )
ValueError: Bad Foo input: ('TIMESTAMP OUTPUT0',)

Traceback (most recent call last):
  File "newpool.py", line 49, in <module>
    main()
  File "newpool.py", line 20, in main
    print( getter.get(timeout=3) )
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 604, in get
    raise TimeoutError
multiprocessing.context.TimeoutError
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/util.py", line 254, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.5/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 537, in _terminate_pool
    assert result_handler.is_alive() or len(cache) == 0
AssertionError
```

**Comment by agude** [comment]
It works with `goo` instead of `foo`.

**Comment by agude** [comment]
You can close this. The solution is to add [`__reduce__`](https://docs.python.org/2/library/pickle.html#pickling-and-unpickling-extension-types) so that `multiprocessing.pool()` can pickle the object.

See: https://bugs.python.org/issue30018#msg291299
